# Generated by Django 4.2.5 on 2023-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('occasion', models.CharField(choices=[('1', 'Enjoy my self'), ('2', 'Date'), ('3', 'Birthday'), ('4', 'Anniversary'), ('5', 'Party')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
